apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}-{{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http