image:
  repository: pgvector/pgvector
  tag: pg16
  pullPolicy: IfNotPresent

containerName: memmachine-postgres

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_DB: memmachine
  POSTGRES_USER: memmachine
  POSTGRES_PASSWORD: memmachine_password
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

healthcheck:
  enabled: true
  interval: 10s
  timeout: 5s
  retries: 5
  startPeriod: 30s